version: '3'

services:
  api:
    image: concierge/api
    container_name: concierge-api
    restart: always
    build:
      context: ./services/api/setup
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - $CONCIERGE_SERVER_PORT:$CONCIERGE_SERVER_PORT
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: concierge-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./services/db/bin:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: concierge-adminer
    restart: always
    env_file:
      - .env
    ports:
      - $CONCIERGE_ADMIN_PORT:$CONCIERGE_ADMIN_PORT
    links:
      - db
    depends_on:
      - db
